### ISSUE TITLE
linux ?

### ISSUE THREAD

**Issue by abasgames** [Crystallinqq/-#3]
listen here little عًِٔــأٌّهٔـَٓرُّٰٔـهُّْٰ
next time don't include linux in your sُhi`ttٍّy payloads

**Comment by Crystallinqq** [comment]
what

**Comment by ghost** [comment]
> listen here little عًِٔــأٌّهٔـَٓرُّٰٔـهُّْٰ
> next time don't include linux in your sُhi`ttٍّy payloads

do u mean malware?

**Comment by Crystallinqq** [comment]
i dont write malware
